.pragma library

//Display Mode severity
var ENUM_APPS_DEFAULT_MODE = 0;
var ENUM_APPS_GRID_MODE = 1;
var ENUM_APPS_LIST_MODE = 2;

//Grid display mode
var ENUM_APPS_BOXWARE_MODE = 1;
var ENUM_APPS_RECTANGLEWARE_MODE = 2;
var ENUM_APPS_COVERWARE_MODE = 3;

//List display mode
var ENUM_APPS_GENERIC_LIST_MODE = 1;
var ENUM_APPS_EXTENDED_LIST_MODE = 2;

//mainscreen category enum
var ENUM_MAIN_SCREEN_SEARCH_CATEGORY = 0
var ENUM_MAIN_SCREEN_VOD_CATEGORY = 1
var ENUM_MAIN_SCREEN_LIVETV_CATEGORY = 2
var ENUM_MAIN_SCREEN_LIVESPORT_CATEGORY = 3
var ENUM_MAIN_SCREEN_LOCAL_MEDIA_CATEGORY = 4
var ENUM_MAIN_SCREEN_MAIL_BOX_CATEGORY = 5
var ENUM_MAIN_SCREEN_SETTINGS_CATEGORY = 6

//VOD Quick Menu settings
var ENUM_VOD_QUICK_SET_ADD_FAV = 0
var ENUM_VOD_QUICK_SET_CLEAR_CACHE = 1
var ENUM_VOD_QUICK_SET_DEL_SELECTED_FAV = 2
var ENUM_VOD_QUICK_SET_CLEAR_FAV = 3
var ENUM_VOD_QUICK_SET_MAIN_VOD_SETTINGS = 4

//LIVE TV Quick Menu settings
var ENUM_LIVE_QUICK_SET_ADD_FAV = 0
var ENUM_LIVE_QUICK_SET_REMOVE_FAV = 1
var ENUM_LIVE_QUICK_SET_CLEAR_FAV = 2

//VOD nevigation level
var ENUM_VOD_ROOT_CATEGORY_LEVEL = 1
var ENUM_VOD_SUBCATEGORY_LEVEL = 2
var ENUM_VOD_MEDIALIST_LEVEL = 3
var ENUM_VOD_ITEMLIST_LEVEL = 4

//Active view
var ENUM_CATEGORIES_ROOT_LEVEL = 1;
var ENUM_CATEGORIES_CATEGORY_LEVEL = 2;
var ENUM_CATEGORIES_STREAMCHANNELS_LEVEL = 3;
var ENUM_CATEGORIES_APPLICATIONS_LEVEL = 4;
var ENUM_CATEGORIES_VOD_LEVEL = 5;
var ENUM_CATEGORIES_MEDIA_BROWSER_LEVEL = 6;
var ENUM_CATEGORIES_STREAMSPORTS_LEVEL = 99;

//Active Playing List
var ENUM_ACTIVE_PLAYING_DEFAULT = 1;
var ENUM_ACTIVE_PLAYING_LIVE_SPORT = 2;
var ENUM_ACTIVE_PLAYING_LIVE_CHANNELS = 3;
var ENUM_ACTIVE_PLAYING_VOD = 4;
var ENUM_ACTIVE_PLAYING_MEDIA_BROWSER = 5;
var ENUM_ACTIVE_PLAYING_APPLICATIONS = 4;

//Message severity
var ENUM_ERROR_MESSAGE = 1;
var ENUM_INFO_MESSAGE = 2;
var ENUM_QUESTION_MESSAGE = 3;

var ENUM_PAGE_STEP_SIZE = 15
var ENUM_APPS_STEP_SIZE = 10

//Apps Categories ids
var ENUM_APPS_VID = 1
var ENUM_APPS_GAMES = 2
var ENUM_APPS_MISC = 3
var ENUM_APPS_FAV = 4
var ENUM_APPS_STORE = 5
var ENUM_APPS_ALL = 6

//Apps Diag type
var ENUM_DIAG_OK = 1
var ENUM_DIAG_YES_NO = 2
var ENUM_DIAG_PROGRESS = 3
var ENUM_DIAG_ACTION_LIST = 4
var ENUM_DIAG_CHOICE_LIST = 5
var ENUM_DIAG_APP_INFO = 6

//Virtual key board text typing methods
var ENUM_TEXT_CLEAR = 0
var ENUM_TEXT_HIDDEN = 1
var ENUM_TEXT_HIDE_WHEN_TYPE = 1
