#ifndef KVAL_CONFIGMANAGER_H
#define KVAL_CONFIGMANAGER_H

#include <memory> 
#include <QObject>
#include <QQuickItem>
#include <QMap>
#include <QMetaEnum>
#include <QMetaObject>
#include <QProcessEnvironment>
#include <QMutexLocker>
#include <QMutex>

#include "KvalSettingsManager.h"

/**
 * @brief The CM_ManagerResources class
 */
class KvalConfigManagerResources: public QObject
{
    Q_OBJECT

public:
    enum str_ids {
        STR_VIDEO_WIDEOPTION_NORMAL = 0,
        STR_VIDEO_WIDEOPTION_FULL_STRETCH ,
        STR_VIDEO_WIDEOPTION_4_3 ,
        STR_VIDEO_WIDEOPTION_16_9 ,
        STR_VIDEO_WIDEOPTION_NONLINEAR ,
        STR_VIDEO_WIDEOPTION_NORMAL_NOSCALEUP ,
        STR_VIDEO_WIDEOPTION_4_3_IGNORE ,
        STR_VIDEO_WIDEOPTION_4_3_LETTER_BOX ,
        STR_VIDEO_WIDEOPTION_4_3_PAN_SCAN ,
        STR_VIDEO_WIDEOPTION_4_3_COMBINED ,
        STR_VIDEO_WIDEOPTION_16_9_IGNORE ,
        STR_VIDEO_WIDEOPTION_16_9_LETTER_BOX ,
        STR_VIDEO_WIDEOPTION_16_9_PAN_SCAN ,
        STR_VIDEO_WIDEOPTION_16_9_COMBINED ,
        STR_VIDEO_WIDEOPTION_MAX ,
        STR_AR_VOD_TOK ,
        STR_NO_GAME_SCHEDULED ,
        STR_SIMULCAST ,
        STR_INFO_START_GAME ,
        STR_INFO_LIVE_BROADCAST ,
        STR_ERROR_EMPTY_LIST_STREAM ,
        STR_ASK_TO_SWITCH_MESSAGE ,
        STR_SWITCH_STREAM_TIPS_PART_1 ,
        STR_SWITCH_STREAM_TIPS_PART_2 ,
        STR_EPG_NOT_AVAILABLE ,
        STR_LOADING ,
        STR_LOADING_DATA ,
        STR_LOADING_START ,
        STR_LOADING_VOD ,
        STR_LOADING_LIVE_TV ,
        STR_LOADING_LIVE_SPORT ,
        STR_LOADING_MAIL_BOX ,
        STR_LOADING_MEDIA_BROWSER ,
        STR_LOADING_SETTINGS ,
        STR_KVAL_PARAM ,
        STR_WIFI_PASS   ,
        STR_BLUE_PANEL ,
        STR_SWITCH_STREAM ,
        STR_SYSTEM_INFO ,
        STR_EXTRA_SETTINGS ,
        STR_ASPECT_RATIO ,
        STR_AUDIO_TRACKS ,
        STR_SUBS ,
        STR_SUBS_ON_OFF ,
        STR_AUDIO_SWITCH ,
        STR_STREAM_INFO ,
        STR_STREAM_NAME ,
        STR_STREAM_BITRATE ,
        STR_STREAM_RESOLUTION ,
        STR_STREAM_RATING ,
        STR_STREAM_SIGNAL_STRENGTH ,
        STR_MEDIUM_SEVERITY_SERVER_MESSAGE ,
        STR_HIGH_SEVERITY_SERVER_MESSAGE ,
        STR_VERY_HIGH_SEVERITY_SERVER_MESSAGE ,
        STR_MAIN_SCREEN_HOME ,
        STR_MAIN_SCREEN_TEXT_SEARCH ,
        STR_MAIN_SCREEN_TEXT_SEARCH_LABEL ,
        STR_MAIN_SCREEN_VOD_LAST_ADD ,
        STR_MAIN_SCREEN_TVSHOW_LAST_ADD ,
        STR_MAIN_SCREEN_MANGAS_LAST_ADD ,
        STR_MAIN_SCREEN_MOVIE_LABEL_TITLE ,
        STR_MAIN_SCREEN_SERIE_LABEL_TITLE ,
        STR_MAIN_SCREEN_SERIE_EPISODE_NBR ,
        STR_MAIN_SCREEN_MANGAS_LABEL_TITLE ,
        STR_MAIN_SCREEN_MANGAS_EPISODE_NBR ,
        STR_MAIN_SCREEN_S_CHANNEL_PACK ,
        STR_MAIN_SCREEN_PACK_1_CHANNELS ,
        STR_MAIN_SCREEN_PACK_2_CHANNELS ,
        STR_MAIN_SCREEN_PIC_LABEL_NAME ,
        STR_MAIN_SCREEN_MUSIC_LABEL_NAME ,
        STR_MAIN_SCREEN_VIDEOS_LABEL_NAME ,
        STR_MAIN_SCREEN_MAILBOX_ACTIVE ,
        STR_MAIN_SCREEN_MAILBOX_INFO ,
        STR_MAIN_SCREEN_MAILBOX_UNREAD_MSG ,
        STR_MAIN_SCREEN_MAILBOX_TOTAL_RECV_MSG ,
        STR_MAIN_SCREEN_SETTINGS_SYSTEM_LABEL_NAME ,
        STR_MAIN_SCREEN_SETTINGS_NETWORK_LABEL_NAME ,
        STR_MAIN_SCREEN_SETTINGS_PROFILE_LABEL_NAME ,
        STR_MAIN_SCREEN_SETTINGS_VOD_LABEL_NAME ,
        STR_MAIN_SCREEN_SETTINGS_LIVETV_LABEL_NAME ,
        STR_MAIN_SCREEN_SETTINGS_INFO_LABEL_NAME ,
        STR_MAIN_SCREEN_LIVETV_CHANNEL_NBR ,
        STR_MAIN_SCREEN_USB_NOT_CONNECTED ,
        STR_MAIN_SCREEN_USB_CONNECTED ,
        STR_MAIN_SCREEN_USB_INFO_CONTENT ,
        STR_VOD_VIDEO_LAUNCH_PROBLEM ,
        STR_NOTIF_ERROR_HEADER ,
        STR_MISSING_VOD_FILE ,
        STR_MISSING_VOD_HINT ,
        STR_MISSING_LIVETV_FILE ,
        STR_MISSING_LIVE_TV_HINT ,
        STR_LIVE_TV_HINT_TITLE ,
        STR_EMPTY_FAV_LIST_STR ,
        STR_PRESS_HOME_BUTTON_STR ,
        STR_SETTINGS_SCAN_WIFI ,
        STR_SETTINGS_EMPTY_SRV ,
        STR_SETTINGS_ACTIVE_LIVETV ,
        STR_SETTINGS_ACTIVE_VOD ,
        STR_LIVETV_HINT_1,
        STR_LIVETV_HINT_2,
        STR_LIVETV_HINT_3,
        STR_VIDEO_APPS,
        STR_MISC_APPS,
        STR_STORE_APPS,
        STR_MY_APPS,
        STR_APPS_OPTIONS,
        STR_APPS_BACK,
        STR_APPS_VERSION,
        STR_APPS_INFORMATIONS,
        STR_APPS_SETTINGS,
        STR_APPS_UNINSTALL,
        STR_APPS_UPDATE,
        STR_APPS_ADD_FAV,
        STR_APPS_REMOVE_FAV,
        STR_APPS_ADD_STORE,
        STR_APPS_ALL_APPS ,
        STR_APPS_TV_VIDEO_APPS ,
        STR_APPS_GAMES_APPS ,
        STR_APPS_PROGRAM_APPS ,
        STR_APPS_FAVORITES_APPS ,
        STR_APPS_STORE_APPS ,
        STR_MAIN_SCREEN_SEARCH,
        STR_MAIN_SCREEN_VOD,
        STR_MAIN_SCREEN_LIVE,
        STR_MAIN_SCREEN_APPS,
        STR_MAIN_SCREEN_MULTIMEDIA,
        STR_MAIN_SCREEN_MAILBOX,
        STR_MAIN_SCREEN_SETTINGS,
        STR_SETTINGS_ACT_DEAC,
        STR_SETTINGS_SYSTEM,
        STR_SETTINGS_SYSTEM_REFRESH ,
        STR_SETTINGS_SYSTEM_LANGUAGE ,
        STR_SETTINGS_SYSTEM_LANGUAGE_VALUES ,
        STR_SETTINGS_SYSTEM_REGION,
        STR_SETTINGS_SYSTEM_REGION_VAL,
        STR_SETTINGS_SYSTEM_TIMEZONE,
        STR_SETTINGS_SYSTEM_TIMEZONE_VAL,
        STR_SETTINGS_SYSTEM_SCREEN_RES,
        STR_SETTINGS_SYSTEM_REFRESH_DATE_TIME,
        STR_SETTINGS_NETWORK,
        STR_SETTINGS_NETWORK_STATUS,
        STR_SETTINGS_NETWORK_CONNECTION_TYPE,
        STR_SETTINGS_NETWORK_WIFI_SCAN,
        STR_SETTINGS_NETWORK_ACCESS_POINT,
        STR_SETTINGS_NETWORK_METHOD,
        STR_SETTINGS_NETWORK_METHOD_VAL,
        STR_SETTINGS_NETWORK_MAC_ADDRESS,
        STR_SETTINGS_NETWORK_IPV4_ADDRESS,
        STR_SETTINGS_NETWORK_IPV6_ADDRESS,
        STR_SETTINGS_NETWORK_SUBNET_MASK,
        STR_SETTINGS_NETWORK_GATEWAY,
        STR_SETTINGS_NETWORK_PRIM_DNS,
        STR_SETTINGS_NETWORK_SECOND_DNS,
        STR_SETTINGS_NETWORK_PROXY_ACTIV,
        STR_SETTINGS_NETWORK_PROXY_ADDRESS,
        STR_SETTINGS_NETWORK_PROXY_PORT,
        STR_SETTINGS_PROFILE_SUBS,
        STR_SETTINGS_PROFILE_BOX_NAME,
        STR_SETTINGS_PROFILE_LIVETV_SUBS_STATUS,
        STR_SETTINGS_PROFILE_LIVETV_SUBS_CODE,
        STR_SETTINGS_PROFILE_VOD_SUBS_STATUS,
        STR_SETTINGS_PROFILE_VOD_SUBS_CODE,
        STR_SETTINGS_VOD,
        STR_SETTINGS_VOD_CLEAR_CACHE,
        STR_SETTINGS_VOD_CLEAR_DOWN,
        STR_SETTINGS_VOD_CACHE_DURATION,
        STR_SETTINGS_VOD_BUF_SIZE,
        STR_SETTINGS_VOD_STREAM,
        STR_SETTINGS_VOD_FILE_USB,
        STR_SETTINGS_VOD_SRV_ADDR,
        STR_SETTINGS_VOD_SRV_ADDR_ACTIVATE,
        STR_SETTINGS_LIVETV,
        STR_SETTINGS_LIVETV_EPG_ACTIVATION,
        STR_SETTINGS_LIVETV_EPG_DURATION,
        STR_SETTINGS_LIVETV_EPG_LIST,
        STR_SETTINGS_LIVETV_FILE_USB,
        STR_SETTINGS_LIVETV_SRV_ADDR,
        STR_SETTINGS_LIVETV_SRV_ADDR_ACTIVATE,
        STR_SETTINGS_INFOS,
        STR_SETTINGS_INFOS_IP_ADDRESS,
        STR_SETTINGS_INFOS_SCREEN_RES,
        STR_SETTINGS_INFOS_STARTS_TIME,
        STR_SETTINGS_INFOS_SOFT_VER,
        STR_SETTINGS_INFOS_LATEST_UPDATE,
        STR_SETTINGS_INFOS_SERIAL_NUMBER,
        STR_VOD_FAVORITES,
        STR_VOD_FAVORITES_CAST,
        STR_VOD_FAVORITES_TVSHOWS_ANIMES,
        STR_QUICKSET_VOD_ADD_TO_FAV,
        STR_QUICKSET_VOD_EMPTY_CACHE,
        STR_QUICKSET_VOD_REMOVE_FROM_FAV,
        STR_QUICKSET_VOD_CLEAR_FAV,
        STR_QUICKSET_TV_ADD_TO_FAV,
        STR_QUICKSET_TV_REMOVE_FROM_FAV,
        STR_QUICKSET_TV_CLEAR_FAV,
        STR_VIDEO_PLAYBACK_HINT
    };
    Q_ENUMS(str_ids)

    enum path_ids {
        KVAL_SOP_BIN_NAME = 0,
        KVAL_EPG_FILE,
        DEFAULT_VOD_MOVIE_COVER,
        KVAL_SETTINGS_VALUES_FILE,
        KVAL_SUBS_SETTINGS_VALUES_FILE,
        KVAL_XML_LIVE_SPORT_CUSTOM_FILE,
        KVAL_XML_LIVE_TV_CUSTOM_FILE,
        KVAL_XML_VOD_CUSTOM_FILE,
        KVAL_XML_LIVE_TV_FILE,
        KVAL_XML_LIVE_TV_FAVCHANNEL_FILE,
        KVAL_INI_UPDATABLE_SET,
        KVAL_SETTINGS_INI_FILE,
        KVAL_NET_WPA_CONF_FILE,
        KVAL_NET_WEP_CONF_FILE,
        KVAL_FIRMWARE_STATUS_FOLDER,
        KVAL_FIRMWARE_STATUS_FILE,
        KVAL_LOCAL_DOWNLOAD_FIRM_FOLDER,
        KVAL_YOUTUBE_EXEC_PATH,
        KVAL_VOD_EXEC_CLEAR_CACHE,
        KVAL_VOD_EXEC_CLEAR_DOWNLOADS,
        KVAL_LOAD_SCREEN,
        KVAL_SOP_LIVETVRU_UPCOMING_EVENT_LINK,
        KVAL_LOCAL_HOST_LINK,
        KVAL_WIZI_LINK,
        PICON_CHANNEL_ABS_PATH,
        MAIN_BACKGROUND_IMAGE ,
        PICON_TEAM_LOGO_ABS_PATH,
        PICON_TEAM_HD_LOGO_ABS_PATH,
        MESSAGE_POPUP_INFO_LOGO ,
        MESSAGE_POPUP_QUESTION_LOGO ,
        MESSAGE_POPUP_ERROR_LOGO ,
        KEY_BLUE_BUTTON ,
        KEY_YELLOW_BUTTON ,
        KEY_GREEN_BUTTON ,
        KEY_RED_BUTTON ,
        KEY_RED_BUTTON_ICON ,
        KEY_MENU_BUTTON ,
        FOLDER_ICON ,
        INFO_LOGO_PNG ,
        INFO_LOGO_PNG2,
        ALERT_LOGO_PNG ,
        ALERT_LOGO_PNG2 ,
        SUCCESS_LOGO_PNG ,
        SUCCESS_LOGO_PNG2,
        ICO_CRYPT_ON ,
        ICO_CRYPT_OFF ,
        ICO_DOLBY_ON ,
        ICO_DOLBY_OFF ,
        ICO_FORMAT_ON ,
        ICO_FORMAT_OFF ,
        ICO_HD_ON ,
        ICON_HD ,
        ICON_4K ,
        ICON_3D ,
        ICON_SD ,
        ICO_ASPECT_1_78 ,
        ICO_CODEC_AAC,
        ICO_CODEC_AC3,
        ICO_CODEC_DTS,
        ICO_CODEC_DTSHDHRA,
        ICO_CODEC_DTSHDMA,
        ICO_CODEC_WMA,
        ICO_CODEC_FLAC,
        ICO_CODEC_MP2,
        ICO_CODEC_MP3,
        ICO_CODEC_LPCM,
        ICO_CODEC_OPUS,
        ICO_CODEC_VORBIS,
        ICO_CODEC_H264 ,
        ICO_CODEC_H265 ,
        ICO_CODEC_MPEG2 ,
        ICO_CODEC_VC1 ,
        ICO_CODEC_VP9 ,
        ICO_RES_480P ,
        ICO_RES_540P ,
        ICO_RES_576P ,
        ICO_RES_720P ,
        ICO_RES_1080P ,
        ICO_RES_1440P ,
        ICO_RES_2160P ,
        ICO_HD_OFF ,
        ICO_SUBS_ON ,
        ICO_SUBS_OFF ,
        BACKGROUNG_ICON_VOD ,
        BACKGROUNG_ICON_VOD_ANIMATED ,
        VIDEO_ICON ,
        VIDEO_2_ICON ,
        MOVIE_FOLDER_ICON ,
        ICO_PREVIOUS,
        ICO_NEXT,
        ICO_PREVIOUS_SMALL,
        ICO_NEXT_SMALL,
        ICO_PREVIOUS_BLUE,
        ICO_NEXT_BLUE,
        ICO_RATING_0 ,
        ICO_RATING_1 ,
        ICO_RATING_2 ,
        ICO_RATING_3 ,
        ICO_RATING_4 ,
        ICO_RATING_5 ,
        ICO_RATING_6 ,
        ICO_RATING_7 ,
        ICO_RATING_8 ,
        ICO_RATING_9 ,
        ICO_RATING_10 ,
        ICO_STAR_HALF ,
        ICO_STAR_EMPTY ,
        ICO_START_VIDEO_V2 ,
        ICO_START_VIDEO_V1 ,
        ICO_LOGOUT ,
        DEFAULT_COVER_IMAGE ,
        ICO_PLAY ,
        ICO_PAUSE ,
        ICO_NEXT_SKIP ,
        ICO_PREVIOUS_SKIP ,
        OVERLAY_BACKGROUND ,
        OVERLAY_BACKGROUND_HD ,
        OVERLAY_BACKGROUND_2 ,
        OVERLAY_BACKGROUND_BLACK ,
        OVERLAY_BACKGROUND_BLACK_2 ,
        OVERLAY_VIGNETTE_FULL ,
        OVERLAY_VIGNETTE_BOTTOM ,
        OVERLAY_VIGNETTE_FULL_ROUNDED ,
        OVERLAY_BASE_COLOR ,
        OVERLAY_BASE_COLOR_2 ,
        OVERLAY_LIST_FOCUS ,
        OVERLAY_LIST_FOCUS_FLIPPED ,
        OVERLAY_SEPARATOR_FADED ,
        HD_ICON ,
        UHD_ICON,
        SD_ICON ,
        POSTER_FRAME ,
        POSTER_FRAME_MASK ,
        POSTER_FRAME_GLOSS ,
        INDICATOR_BACK ,
        FRAME_SQUARE_BIG ,
        FRAME_BANNER_VOD_CHOICE ,
        DEFAULT_BACKDORE_PNG ,
        SEPERATOR_MAIN_VIEW_SCREEN ,
        HOME_RSS_INFO_BAR ,
        ALBUM_FRAME ,
        ALBUM_FRAME_MASK ,
        INFO_OVERLAY_BLACK ,
        INFO_OVERLAY_BLUE ,
        GTIP_POINT ,
        GTIP_POINT_FIRST ,
        GTIP_POINT_MIDDLE ,
        GTIP_POINT_LAST ,
        STAR_RATE ,
        HOME_VIDEO_ICON ,
        HOME_TVSHOW_ICON ,
        HOME_VIDEO_CIRCLE_ICON ,
        HOME_BACKGROUND_MORNING_1 ,
        BUSY_SPINNER ,
        HOME_ICON ,
        SEARCH_HOME_ICON ,
        XML_MAIN_SCREEN_FILE ,
        LINE1_BACKGROUND ,
        LINE1_COMPLETE_BACKGROUND ,
        LINE2_BACKGROUND ,
        LINE2_GREY_BACKGROUND ,
        SPORT_WALLPAPER_BACKGROUND ,
        LIVE_TV_BACK_2 ,
        LIVE_TV_BACK_3 ,
        LIVE_TV_BACK_1 ,
        LIVE_SPORT_HORIZENTAL_SEPARATOR ,
        LIVE_SPORT_COMPET1_BACK ,
        LIVE_SPORT_COMPET2_BACK ,
        LIVE_SPORT_COMPET3_BACK ,
        LIVE_SPORT_LEAGUE_LOGOS_PATH ,
        LIVE_SPORT_CLUBS_LOGOS_PATH ,
        LIVE_SPORT_BACK_1 ,
        LIVE_SPORT_BACK_2 ,
        LIVE_SPORT_VERTICAL_SEP ,
        LIVE_SPORT_FRAME_GALLERY ,
        LIVE_SPORT_FOOT_LOGOS_BACK ,
        LIVE_SPORT_FOOT_ALL_COMP ,
        BOOT_BACKGROUNG_MORNING ,
        BOOT_BACKGROUNG_AFTERNOON ,
        BOOT_BACKGROUNG_EVENING ,
        BOOT_KVAL_IP_ICONS ,
        KVAL_LOGO_LITTLE ,
        STARTUP_AFTERNOON_WELCOME ,
        STARTUP_EVENING_WELCOME ,
        STARTUP_MORNING_WELCOME ,
        KVAL_LOGO_BIG ,
        NOTIFICATION_MSG_BACK ,
        PLAYER_HINTS_BACK,
        LIVE_TV_BACK_IMG ,
        HOME_MESSAGE_ICON ,
        USB_HOME_ICON ,
        HDD_HOME_ICON ,
        HOME_LOCAL_MEDIA_PICS_BACK ,
        HOME_LOCAL_MEDIA_PICS ,
        HOME_LOCAL_MEDIA_MUSIC_BACK ,
        HOME_LOCAL_MEDIA_MUSIC ,
        HOME_LOCAL_MEDIA_VIDEOS_BACK ,
        HOME_LOCAL_MEDIA_VIDEOS ,
        HOME_MAILBOX_COMP1_BACK ,
        HOME_MAILBOX_IMG ,
        HOME_MAILBOX_ONE_MAIL ,
        HOME_MAILBOX_MSG_BUBBLE ,
        HOME_MAILBOX_TOTAL_MAILS ,
        MAILBOX_BOX_ICON ,
        MAILBOX_BOX_BACKGROUND ,
        MAILBOX_BOX_SEEN_FLAG ,
        MAILBOX_BOX_SEEN_FLAG_SELECTED ,
        MEDIA_BROWSER_ICON_HDD ,
        MEDIA_BROWSER_ICON_DIR ,
        MEDIA_BROWSER_ICON_AUDIO ,
        MEDIA_BROWSER_ICON_VIDEO ,
        MEDIA_BROWSER_ICON_IMAGE ,
        MEDIA_BROWSER_ICON_UNKNOWN ,
        MEDIA_BROWSER_BACKGROUND ,
        MEDIA_BROWSER_VIDEO_BACK ,
        MEDIA_BROWSER_MUSIC_BACK ,
        SETTINGS_SYSTEM_ICON ,
        SETTINGS_NETWORK_ICON ,
        SETTINGS_PROFILE_ICON ,
        SETTINGS_VOD_ICON ,
        SETTINGS_LIVETV_ICON ,
        SETTINGS_INFO_ICON_BIG ,
        SETTINGS_INFO_ICON_SMALL,
        SETTINGS_SELECT_ICON ,
        SETTINGS_EDIT_ICON ,
        SETTINGS_ON_ICON ,
        SETTINGS_OFF_ICON ,
        SETTINGS_ACTION_ICON,
        SETTINGS_SETTING_ICON,
        SETTINGS_BACKGROUND ,
        SETTINGS_ICON ,
        SETTINGS_SEPARATOR_FADED,
        SETTINGS_WIFI_ICON_PREFIX,
        VOLUME_ICON ,
        MUTE_ICON ,
        ICON_PAID ,
        ICON_FREE ,
        DEFAULT_TEXT_FONT,
        DEFAULT_TEXT_FONT_LOW,
        DEFAULT_TEXT_FONT_CAPS,
        DEFAULT_TEXT_BOLD_FONT,
        ADVENT_TEXT_FONT,
        MANGAS_TEXT_FONT,
        LIVE_TV_GALLERY_FONT,
        XML_LIVE_SPORT_FILE,
        XML_CHANNEL_FILE,
        XML_FAV_CHANNEL_FILE,
        XML_VOD_FILE,
        XML_VOD_QUICK_SETTING_FILE,
        XML_SETTINGS_DISPLAY_FILE,
        INFO_OVERLAY_RED,
        WALL_FRAME_BASE,
        LIVE_SPORT_LOGO,
        MEDIA_BROWSER_ICON_USB,
        ADDON_ADD_ICON,
        YT_LOGO_ICON,
        YT_LOGO_APP,
        YT_APP_BACK,
        MAIN_APPFRAME,
        MAIN_APPFRAME_MASK,
        MAIN_APPFRAME_SHADOW,
        APP_FRAME,
        APP_FRAME_MASK,
        APP_PLUS_BACKGROUND,
        SCREEN_APP_FOREGROUND_1,
        SCREEN_APP_FOREGROUND_1_REF,
        SCREEN_APP_SHININGCORNER_1,
        SCREEN_APP_FOREGROUND_2,
        SCREEN_APP_SHININGCORNER_2,
        SCREEN_APP_FOREGROUND_3,
        SCREEN_APP_SHININGCORNER_3,
        WEATHER_APP_BACK,
        WEATHER_APP_ICON,
        APPS_BLOCK_BACK,
        APPS_BLOCK_SEP,
        APPS_ICONS,
        APPS_BACKGROUND,
        APPS_SELECTOR,
        APPS_SELECTOR2,
        APPS_FADED,
        APPS_UPGRADE_ICON,
        APPS_VIEW_BACK,
        APPS_VIEW_ALL_ICO,
        APPS_VIEW_FAV_ICO,
        APPS_VIEW_GAMES_ICO,
        APPS_VIEW_INSTALLED_ICO,
        APPS_VIEW_MISC_ICO,
        APPS_VIEW_STORE_ICO,
        APPS_VIEW_VID_ICO,
        APPS_VIEW_SEARCH_ICO,
        APPS_VIEW_SELCTOR_CAT,
        APPS_VIEW_MASKGRID,
        APPS_VIEW_BACKMASKGRID,
        APPS_VIEW_MASKGRIDDIAG,
        APPS_VIEW_SPINNER_BACK,
        APPS_VIEW_SPINNER,
        APPS_CAT_SELECTOR,
        APPS_RECTWARE_SELECTOR,
        APPS_COVERWARE_SELECTOR,
        APPS_DIAG_WINDOW,
        APPS_DIAG_BUTTON,
        APPS_DIAG_SELECTOR,
        APPS_PROGRESS_BAR_BACK,
        APPS_PROGRESS_BAR_HELPER,
        APPS_MENU_ICON,
        APPS_RECTANGLEWARE_REF,
        APPS_LISTRECTANGLEWARE_REF,
        APPS_LISTCOVERWARE_REF,
        APPS_BOXWARE_REF,
        APPS_COVERWARE_REF,
        APPS_LISTBOXWARE_REF,
        APPS_LISTRECT_SELECTOR,
        APPS_RECTANGLEWARE_MASK,
        APPS_COVERWARE_MASK,
        APPS_CTX_SHADOW,
        APPS_CTX_HEADER,
        APPS_CTX_BORDER,
        APPS_CTX_BODY,
        APPS_CTX_MENU_SELECTOR,
        APPS_CTX_MASK,
        APPS_LIST_MENU_HEADER,
        APPS_LIST_MENU_BODY,
        APPS_LIST_MENU_BORDER,
        APPS_LIST_MENU_SHADOW,
        APPS_LIST_MENU_SELECTOR,
        APPS_APP_INFOS_BACK,
        APPS_APP_INFOS_MASK,
        APPS_MOTION_GRAPHICS,
        BLUE_BUTTON_ICO,
        BLUE_PANEL_BACK,
        BLUE_PANEL_SELECTOR,
        BLUE_PANEL_SEPARATOR,
        VOD_POINT_SEP,
        VO_LANG_ICON,
        VOST_LANG_ICON,
        VF_LANG_ICON,
        MULTI_LANG_ICON,
        BLURAY_QUAL_ICON,
        LIGHT_QUAL_ICON,
        DVD_QUAL_ICON,
        MAIN_REBOOT_ICON
    };
    Q_ENUMS(path_ids)

    const QMap<str_ids, QString> cfg_str_tab {
        {   STR_VIDEO_WIDEOPTION_NORMAL , tr("normal")},
        {   STR_VIDEO_WIDEOPTION_FULL_STRETCH ,   tr("full stretch")},
        {   STR_VIDEO_WIDEOPTION_4_3 ,   tr("4:3")},
        {   STR_VIDEO_WIDEOPTION_16_9 ,   tr("16:9")},
        {   STR_VIDEO_WIDEOPTION_NONLINEAR ,   tr("non linear")},
        {   STR_VIDEO_WIDEOPTION_NORMAL_NOSCALEUP ,   tr("no scale up")},
        {   STR_VIDEO_WIDEOPTION_4_3_IGNORE ,   tr("4:3 ignore")},
        {   STR_VIDEO_WIDEOPTION_4_3_LETTER_BOX ,   tr("4:3 letter box")},
        {   STR_VIDEO_WIDEOPTION_4_3_PAN_SCAN ,   tr("4:3 Pan Scan")},
        {   STR_VIDEO_WIDEOPTION_4_3_COMBINED ,   tr("4:3 Combined")},
        {   STR_VIDEO_WIDEOPTION_16_9_IGNORE ,   tr("16:9 ignore")},
        {   STR_VIDEO_WIDEOPTION_16_9_LETTER_BOX ,   tr("16:9 letter box")},
        {   STR_VIDEO_WIDEOPTION_16_9_PAN_SCAN ,   tr("16:9 pan scan")},
        {   STR_VIDEO_WIDEOPTION_16_9_COMBINED ,   tr("16:9 combined")},
        {   STR_VIDEO_WIDEOPTION_MAX ,   tr("max")},
        {   STR_AR_VOD_TOK ,   tr("عربية")},
        {   STR_NO_GAME_SCHEDULED ,   tr("Pas de match prévue")},
        {   STR_SIMULCAST ,   tr("Simulcast")},
        {   STR_INFO_START_GAME ,   tr("La diffusion commencera 20 minutes avant le match")},
        {   STR_INFO_LIVE_BROADCAST ,   tr("Diffusion En Direct")},
        {   STR_ERROR_EMPTY_LIST_STREAM ,   tr("Pas de flux disponible pour le moment , essayer plus tard")},
        {   STR_ASK_TO_SWITCH_MESSAGE ,   tr("Vous êtes sur le point de changer de flux, continuer?")},
        {   STR_SWITCH_STREAM_TIPS_PART_1 ,   tr("For some reason, if the loading process took too much time. Most of the time more than 90 second, press")},
        {   STR_SWITCH_STREAM_TIPS_PART_2 ,   tr("button to switch stream.")},
        {   STR_EPG_NOT_AVAILABLE ,   tr("Epg non disponible pour cette chaine")},
        {   STR_LOADING ,   tr("Chargement")},
        {   STR_LOADING_DATA ,   tr("Chargement des données ...")},
        {   STR_LOADING_START ,   tr("Démarrage ...")},
        {   STR_LOADING_VOD ,   tr("Chargement VOD ...")},
        {   STR_LOADING_LIVE_TV ,   tr("Chargement Live Tv ...")},
        {   STR_LOADING_LIVE_SPORT ,   tr("Chargement Live Sport ...")},
        {   STR_LOADING_MAIL_BOX ,   tr("Chargement Messagerie ...")},
        {   STR_LOADING_MEDIA_BROWSER ,   tr("Chargement Contenus Multimédia ...")},
        {   STR_LOADING_SETTINGS ,   tr("Chargement Paramètres ...")},
        {   STR_KVAL_PARAM ,   tr("Paramètres<font color=\"#6aa6cb\"> kval</font>")},
        {   STR_WIFI_PASS   ,   tr("Entrer le mot de passe WiFi")},
        {   STR_BLUE_PANEL ,   tr("Blue Panel")},
        {   STR_SWITCH_STREAM ,   tr("Changer de flux")},
        {   STR_SYSTEM_INFO ,   tr("Sys Info")},
        {   STR_EXTRA_SETTINGS ,   tr("Extra Settings")},
        {   STR_ASPECT_RATIO ,   tr("Aspect Ratio")},
        {   STR_AUDIO_TRACKS ,   tr("Pistes Audio")},
        {   STR_SUBS ,   tr("Sous titres")},
        {   STR_SUBS_ON_OFF ,   tr("Sous-titres Switch")},
        {   STR_AUDIO_SWITCH ,   tr("Audio Switch")},
        {   STR_STREAM_INFO ,   tr("Information Flux:")},
        {   STR_STREAM_NAME ,   tr("Nom")},
        {   STR_STREAM_BITRATE ,   tr("Bit Rate")},
        {   STR_STREAM_RESOLUTION ,   tr("Résolution")},
        {   STR_STREAM_RATING ,   tr("Rating")},
        {   STR_STREAM_SIGNAL_STRENGTH ,   tr("Signal")},
        {   STR_MEDIUM_SEVERITY_SERVER_MESSAGE ,   tr("normal")},
        {   STR_HIGH_SEVERITY_SERVER_MESSAGE ,   tr("high")},
        {   STR_VERY_HIGH_SEVERITY_SERVER_MESSAGE ,   tr("very high")},
        {   STR_MAIN_SCREEN_HOME ,   tr("Home")},
        {   STR_MAIN_SCREEN_TEXT_SEARCH ,   tr("Search engine")},
        {   STR_MAIN_SCREEN_TEXT_SEARCH_LABEL ,   tr("Search Vod, Tv Channels, Applications...")},
        {   STR_MAIN_SCREEN_VOD_LAST_ADD ,   tr("Movies Latest Adds")},
        {   STR_MAIN_SCREEN_TVSHOW_LAST_ADD ,   tr("Tv Shows Most Viewed")},
        {   STR_MAIN_SCREEN_MANGAS_LAST_ADD ,   tr("Mangas Most Viewed")},
        {   STR_MAIN_SCREEN_MOVIE_LABEL_TITLE ,   tr("Movies")},
        {   STR_MAIN_SCREEN_SERIE_LABEL_TITLE ,   tr("Tv Shows")},
        {   STR_MAIN_SCREEN_SERIE_EPISODE_NBR ,   tr("All episodes")},
        {   STR_MAIN_SCREEN_MANGAS_LABEL_TITLE ,   tr("Mangas")},
        {   STR_MAIN_SCREEN_MANGAS_EPISODE_NBR ,   tr("All episodes")},
        {   STR_MAIN_SCREEN_S_CHANNEL_PACK ,   tr("Pack S")},
        {   STR_MAIN_SCREEN_PACK_1_CHANNELS ,   tr("Pack 1")},
        {   STR_MAIN_SCREEN_PACK_2_CHANNELS ,   tr("Pack 2")},
        {   STR_MAIN_SCREEN_PIC_LABEL_NAME ,   tr("Photos")},
        {   STR_MAIN_SCREEN_MUSIC_LABEL_NAME ,   tr("Musique")},
        {   STR_MAIN_SCREEN_VIDEOS_LABEL_NAME ,   tr("Videos")},
        {   STR_MAIN_SCREEN_MAILBOX_ACTIVE ,   tr("Messagerie Active")},
        {   STR_MAIN_SCREEN_MAILBOX_INFO ,   tr("Consulter tout les messages reçu.")},
        {   STR_MAIN_SCREEN_MAILBOX_UNREAD_MSG ,   tr("Messages Non lues")},
        {   STR_MAIN_SCREEN_MAILBOX_TOTAL_RECV_MSG ,   tr("Total messages reçus")},
        {   STR_MAIN_SCREEN_SETTINGS_SYSTEM_LABEL_NAME ,   tr("Paramètres Système")},
        {   STR_MAIN_SCREEN_SETTINGS_NETWORK_LABEL_NAME ,   tr("Paramètres Réseau")},
        {   STR_MAIN_SCREEN_SETTINGS_PROFILE_LABEL_NAME ,   tr("Paramètres Profil")},
        {   STR_MAIN_SCREEN_SETTINGS_VOD_LABEL_NAME ,   tr("Paramètres VOD")},
        {   STR_MAIN_SCREEN_SETTINGS_LIVETV_LABEL_NAME ,   tr("Paramètres Live TV")},
        {   STR_MAIN_SCREEN_SETTINGS_INFO_LABEL_NAME ,   tr("Paramètres Information")},
        {   STR_MAIN_SCREEN_LIVETV_CHANNEL_NBR,  tr("Live tv channels")},
        {   STR_MAIN_SCREEN_USB_NOT_CONNECTED ,   tr("Pas de support USB externe connecté à votre Box")},
        {   STR_MAIN_SCREEN_USB_CONNECTED ,   tr("Un périphérique USB est connecté à Votre Box")},
        {   STR_MAIN_SCREEN_USB_INFO_CONTENT ,   tr("Connectez une clé USB ou un HDD externe afin d'accéder \nà tous vos contenus musiques, photos et vidéos")},
        {   STR_VOD_VIDEO_LAUNCH_PROBLEM ,   tr("Erreur Video. Essayez un autre lien")},
        {   STR_NOTIF_ERROR_HEADER ,   tr("Error : ")},
        {   STR_MISSING_VOD_FILE ,   tr("<font color=\"c3461b\">Pas de fichier trouvé pour la VOD<\font>\n")},
        {   STR_MISSING_VOD_HINT ,   tr("Afin de pouvoir profiter de la foncionnalité VOD, il faudra imperativement charger le fichier correspondant.\nPour faire cela, il faudra aller dans '''paramètres/Vidèo à la demande''' et choisir soit :\n1- Charger le fichier VOD par USB\n2- Charger le fichier VOD à travers un serveur Distant")},
        {   STR_MISSING_LIVETV_FILE ,   tr("<font color=\"#c3461b\">Pas de fichier trouvé pour le Live<\font>\n")},
        {   STR_MISSING_LIVE_TV_HINT ,   tr("Afin de pouvoir profiter de la foncionnalité Live, il faudra imperativement charger le fichier correspondant.\nPour faire cela, il faudra aller dans '''paramètres/Live TV''' et choisir soit :\n1- Charger le fichier Live TV par USB\n2- Charger le fichier Live TV à travers un serveur Distant.")},
        {   STR_LIVE_TV_HINT_TITLE ,   tr("<font color=\"#c3461b\">Astuce:<\font>\n")},
        {   STR_EMPTY_FAV_LIST_STR ,   tr("<font color=\"#c3461b\">La liste des favoris est Vide<\font>\n")},
        {   STR_PRESS_HOME_BUTTON_STR ,   tr("Appuyer sur le boutton '''HOME''' de votre télécommande pour revenir sur la page principale")},
        {   STR_SETTINGS_SCAN_WIFI ,   tr("Scan Réseau WiFi...")},
        {   STR_SETTINGS_EMPTY_SRV ,   tr("Addresse du serveur Vide !")},
        {   STR_SETTINGS_ACTIVE_LIVETV ,  tr("Activation Live TV ...")},
        {   STR_SETTINGS_ACTIVE_VOD  ,    tr("Activation VOD ...")},
        {   STR_LIVETV_HINT_1, tr("Pour revenir a la page principale appuyez sur le boutton HOME de votre télécommande")},
        {   STR_LIVETV_HINT_2, tr("Pour ajouter des chaines a la liste des favoris:\n1- selectionner la chaines en question.\n2- Appuyer sur le boutton MENU de votre télécommande\n3- Appuyer sur 'Ajouter la chaine au favoris'")},
        {   STR_LIVETV_HINT_3, tr("Vous pouvez accéder a la liste des chaines favoris en appuiyant sur le boutton VERT de votre télécommande.")},
        {   STR_VIDEO_APPS, tr("Video applications")},
        {   STR_MISC_APPS, tr("Misc applications")},
        {   STR_STORE_APPS, tr("Store applications")},
        {   STR_MY_APPS, tr("My Apps")},
        {   STR_APPS_OPTIONS, tr("Options")},
        {   STR_APPS_BACK, tr("Retour")},
        {   STR_APPS_VERSION, tr("Version")},
        {   STR_APPS_INFORMATIONS, tr("Informations")},
        {   STR_APPS_SETTINGS, tr("Paramètres...")},
        {   STR_APPS_UNINSTALL, tr("Désintaller...")},
        {   STR_APPS_UPDATE, tr("Mise à jours...")},
        {   STR_APPS_ADD_FAV, tr("Ajouter aux favoris...")},
        {   STR_APPS_REMOVE_FAV, tr("Supprimer des favoris...")},
        {   STR_APPS_ADD_STORE, tr("Ajouter un store...")},
        {   STR_APPS_ALL_APPS , tr("Toutes les applis")},
        {   STR_APPS_TV_VIDEO_APPS , tr("Tv & Video")},
        {   STR_APPS_GAMES_APPS , tr("Jeux")},
        {   STR_APPS_PROGRAM_APPS , tr("Programmes")},
        {   STR_APPS_FAVORITES_APPS , tr("Favoris")},
        {   STR_APPS_STORE_APPS , tr("Store")},
        {   STR_MAIN_SCREEN_SEARCH, tr("Search")},
        {   STR_MAIN_SCREEN_VOD, tr("Video on demand")},
        {   STR_MAIN_SCREEN_LIVE, tr("Live TV")},
        {   STR_MAIN_SCREEN_APPS, tr("Applications")},
        {   STR_MAIN_SCREEN_MULTIMEDIA, tr("Multimedia contents")},
        {   STR_MAIN_SCREEN_MAILBOX, tr("Mail Box")},
        {   STR_MAIN_SCREEN_SETTINGS, tr("Settings")},
        {   STR_SETTINGS_ACT_DEAC, tr("Enabled|Disabled")},
        {   STR_SETTINGS_SYSTEM, tr("General")},
        {   STR_SETTINGS_SYSTEM_REFRESH ,   tr("Refresh system settings...")},
        {   STR_SETTINGS_SYSTEM_LANGUAGE ,   tr("Language...")},
        {   STR_SETTINGS_SYSTEM_LANGUAGE_VALUES ,   tr("fr-FR|en-US")},
        {   STR_SETTINGS_SYSTEM_REGION,   tr("Region")},
        {   STR_SETTINGS_SYSTEM_REGION_VAL,   tr("France|Tunisia|Turkey|Saudi Arabia|Britain (UK)")},
        {   STR_SETTINGS_SYSTEM_TIMEZONE,   tr("Time Zone")},
        {   STR_SETTINGS_SYSTEM_TIMEZONE_VAL,   tr("Europe/Paris|Africa/Tunis|Europe/Istanbul|Asia/Riyadh|Europe/London")},
        {   STR_SETTINGS_SYSTEM_SCREEN_RES,   tr("Screen resolution")},
        {   STR_SETTINGS_SYSTEM_REFRESH_DATE_TIME,   tr("Refresh Date and Time...")},
        {   STR_SETTINGS_NETWORK,   tr("Network")},
        {   STR_SETTINGS_NETWORK_STATUS,   tr("Network status")},
        {   STR_SETTINGS_NETWORK_CONNECTION_TYPE,   tr("Connection Type")},
        {   STR_SETTINGS_NETWORK_WIFI_SCAN,   tr("Scan WiFi...")},
        {   STR_SETTINGS_NETWORK_ACCESS_POINT,   tr("Access point")},
        {   STR_SETTINGS_NETWORK_METHOD,   tr("Method")},
        {   STR_SETTINGS_NETWORK_METHOD_VAL,   tr("DHCP|Manuelle")},
        {   STR_SETTINGS_NETWORK_MAC_ADDRESS,   tr("MAC address")},
        {   STR_SETTINGS_NETWORK_IPV4_ADDRESS,   tr("IPv4 address")},
        {   STR_SETTINGS_NETWORK_IPV6_ADDRESS,   tr("IPv6 address")},
        {   STR_SETTINGS_NETWORK_SUBNET_MASK,   tr("Subnet mask")},
        {   STR_SETTINGS_NETWORK_GATEWAY,   tr("Gateway")},
        {   STR_SETTINGS_NETWORK_PRIM_DNS,   tr("Primary DNS")},
        {   STR_SETTINGS_NETWORK_SECOND_DNS,   tr("Secondary DNS")},
        {   STR_SETTINGS_NETWORK_PROXY_ACTIV,   tr("Proxy activation")},
        {   STR_SETTINGS_NETWORK_PROXY_ADDRESS,   tr("Proxy Address")},
        {   STR_SETTINGS_NETWORK_PROXY_PORT,   tr("Proxy Port")},
        {   STR_SETTINGS_PROFILE_SUBS,   tr("Profil")},
        {   STR_SETTINGS_PROFILE_BOX_NAME,   tr("Box Name")},
        {   STR_SETTINGS_PROFILE_LIVETV_SUBS_STATUS,   tr("Live Tv status")},
        {   STR_SETTINGS_PROFILE_LIVETV_SUBS_CODE,   tr("Live Tv code")},
        {   STR_SETTINGS_PROFILE_VOD_SUBS_STATUS,   tr("VOD status")},
        {   STR_SETTINGS_PROFILE_VOD_SUBS_CODE,   tr("VOD code")},
        {   STR_SETTINGS_VOD,   tr("Video on demand")},
        {   STR_SETTINGS_VOD_CLEAR_CACHE,   tr("Clear cache...")},
        {   STR_SETTINGS_VOD_CLEAR_DOWN,   tr("Clear Downloads...")},
        {   STR_SETTINGS_VOD_CACHE_DURATION,   tr("Cache Duration in days")},
        {   STR_SETTINGS_VOD_BUF_SIZE,   tr("Precaching percentage size")},
        {   STR_SETTINGS_VOD_STREAM,   tr("Video streaming (Requires good Internet speed)...")},
        {   STR_SETTINGS_VOD_FILE_USB,   tr("Upload VOD file using USB key...")},
        {   STR_SETTINGS_VOD_SRV_ADDR,   tr("VODserver address...")},
        {   STR_SETTINGS_VOD_SRV_ADDR_ACTIVATE,   tr("Activate VOD through server...")},
        {   STR_SETTINGS_LIVETV,   tr("Live TV")},
        {   STR_SETTINGS_LIVETV_EPG_ACTIVATION,   tr("Activate EPG")},
        {   STR_SETTINGS_LIVETV_EPG_DURATION,   tr("Epg duration in days")},
        {   STR_SETTINGS_LIVETV_EPG_LIST,   tr("EPG display list")},
        {   STR_SETTINGS_LIVETV_FILE_USB,   tr("Upload LiveTV file using USB key...")},
        {   STR_SETTINGS_LIVETV_SRV_ADDR,   tr("LiveTvserver address...")},
        {   STR_SETTINGS_LIVETV_SRV_ADDR_ACTIVATE,   tr("Activate LiveTv through server...")},
        {   STR_SETTINGS_INFOS,   tr("Informations Box")},
        {   STR_SETTINGS_INFOS_IP_ADDRESS,   tr("IP address")},
        {   STR_SETTINGS_INFOS_SCREEN_RES,   tr("Screen resolution")},
        {   STR_SETTINGS_INFOS_STARTS_TIME,   tr("System started duration")},
        {   STR_SETTINGS_INFOS_SOFT_VER,   tr("Software version")},
        {   STR_SETTINGS_INFOS_LATEST_UPDATE,   tr("Latest firmware update")},
        {   STR_SETTINGS_INFOS_SERIAL_NUMBER,   tr("Serial number")},
        {   STR_VOD_FAVORITES, tr("Favoris")},
        {   STR_VOD_FAVORITES_CAST, tr("Films Favoris • Séries Favoris • Mangas Favoris")},
        {   STR_VOD_FAVORITES_TVSHOWS_ANIMES, tr("Séries-Animes-Mangas")},
        {   STR_QUICKSET_VOD_ADD_TO_FAV, tr("Ajouter la sélection aux favoris")},
        {   STR_QUICKSET_VOD_EMPTY_CACHE, tr("Vider le cache")},
        {   STR_QUICKSET_VOD_REMOVE_FROM_FAV, tr("Enlevé L'entrée des favoris")},
        {   STR_QUICKSET_VOD_CLEAR_FAV, tr("Supprimer la liste des favoris")},
        {   STR_QUICKSET_TV_ADD_TO_FAV, tr("Ajouter la chaine aux favoris")},
        {   STR_QUICKSET_TV_REMOVE_FROM_FAV, tr("Enlevé la chaine des favoris")},
        {   STR_QUICKSET_TV_CLEAR_FAV, tr("Vider la liste des favoris")},
        {   STR_VIDEO_PLAYBACK_HINT, tr("Press the <b>Info</b> button to :<br>    • Switch Audio/Subtitles.<br>    • Disable/Enable subtitles.<br>    • Resize the video scale.")}
    };

    const QMap<path_ids, QString> cfg_exc_path_tab {
        { KVAL_YOUTUBE_EXEC_PATH,       "/kval_vod/plugin.video.youtube.v3/default.pyo"},
        { KVAL_VOD_EXEC_CLEAR_CACHE,    "/kval_vod/clear_vod_cache.pyo"},
        { KVAL_VOD_EXEC_CLEAR_DOWNLOADS,"/kval_vod/clear_vod_downloads.pyo"}
    };

    const QMap<path_ids, QString> cfg_path_tab {
        {  KVAL_SOP_BIN_NAME, "/sopcast/qemu-i386"},
        {  KVAL_EPG_FILE, "/kval_cfg/epg.xml"},
        {  DEFAULT_VOD_MOVIE_COVER, "/kval_res/background/default.jpg"},
        {  KVAL_SETTINGS_VALUES_FILE, "/kval_cfg/settingsValues.xml"},
        {  KVAL_SUBS_SETTINGS_VALUES_FILE, "/kval_cfg/subs.ini"},
        {  KVAL_XML_LIVE_SPORT_CUSTOM_FILE, "/kval_cfg/main_screen_live_sport_custom.xml"},
        {  KVAL_XML_LIVE_TV_CUSTOM_FILE, "/kval_cfg/main_screen_live_tv_custom.xml"},
        {  KVAL_XML_VOD_CUSTOM_FILE, "/kval_cfg/main_screen_vod_custom.xml"},
        {  KVAL_XML_LIVE_TV_FILE, "/kval_cfg/livech.xml"},
        {  KVAL_XML_LIVE_TV_FAVCHANNEL_FILE, "/kval_cfg/favorite_channels.xml"},
        {  KVAL_INI_UPDATABLE_SET, "/kval_cfg/updatable_set.ini"},
        {  KVAL_SETTINGS_INI_FILE, "/kval_cfg/kvalsettings.ini"},
        {  KVAL_NET_WPA_CONF_FILE, "/kval_cfg/.wpa.conf" },
        {  KVAL_NET_WEP_CONF_FILE, "/kval_cfg/.wep.conf" },
        {  KVAL_FIRMWARE_STATUS_FOLDER, "/firmware/" },
        {  KVAL_FIRMWARE_STATUS_FILE, "/firmware/status" },
        {  KVAL_LOCAL_DOWNLOAD_FIRM_FOLDER, "/cache/server_client_cache/firmwareUpdate/" },
        {  KVAL_LOAD_SCREEN, "/kval_res/background/load_screen.png" },
        {  KVAL_SOP_LIVETVRU_UPCOMING_EVENT_LINK, ""},
        {  PICON_CHANNEL_ABS_PATH, "/kval_res/icons/picons/"},
        {  MAIN_BACKGROUND_IMAGE , "/kval_res/background/Blue-Gradient-Abstract-Wallpaper-1920x1080.jpg"},
        {  PICON_TEAM_LOGO_ABS_PATH, "/kval_res/home/liveSports/clubsLogos/"},
        {  PICON_TEAM_HD_LOGO_ABS_PATH, "/kval_res/clubs_logos/hd_logos/"},
        {  MESSAGE_POPUP_INFO_LOGO , "/kval_res/icons/message/info-53.png"},
        {  MESSAGE_POPUP_QUESTION_LOGO , "/kval_res/icons/message/question-53.png"},
        {  MESSAGE_POPUP_ERROR_LOGO , "/kval_res/icons/message/attention-53.png"},
        {  KEY_BLUE_BUTTON , "/kval_res/buttons/key_blue.png"},
        {  KEY_YELLOW_BUTTON , "/kval_res/buttons/key_yellow.png"},
        {  KEY_GREEN_BUTTON , "/kval_res/buttons/key_green.png"},
        {  KEY_RED_BUTTON , "/kval_res/buttons/key_red.png"},
        {  KEY_RED_BUTTON_ICON , "/kval_res/buttons/key_red_.png"},
        {  KEY_MENU_BUTTON , "/kval_res/buttons/key_menu.png"},
        {  FOLDER_ICON , "/kval_res/icons/folder.png"},
        {  INFO_LOGO_PNG , "/kval_res/icons/info.png"},
        {  INFO_LOGO_PNG2 , "/kval_res/icons/info@uhd.png"},
        {  ALERT_LOGO_PNG , "/kval_res/icons/alert.png"},
        {  ALERT_LOGO_PNG2 , "/kval_res/icons/alert@uhd.png"},
        {  SUCCESS_LOGO_PNG , "/kval_res/icons/success.png"},
        {  SUCCESS_LOGO_PNG2 , "/kval_res/icons/success@uhd.png"},
        {  ICO_CRYPT_ON , "/kval_res/icons/ico_crypt_on.png"},
        {  ICO_CRYPT_OFF , "/kval_res/icons/ico_crypt_off.png"},
        {  ICO_DOLBY_ON , "/kval_res/icons/ico_dolby_on.png"},
        {  ICO_DOLBY_OFF , "/kval_res/icons/ico_dolby_off.png"},
        {  ICO_FORMAT_ON , "/kval_res/icons/ico_format_on.png"},
        {  ICO_FORMAT_OFF , "/kval_res/icons/ico_format_off.png"},
        {  ICO_HD_ON , "/kval_res/icons/ico_hd_on.png"},
        {  ICON_HD , "/kval_res/icons/icon_hd.png"},
        {  ICON_4K , "/kval_res/icons/icon_4k.png"},
        {  ICON_3D , "/kval_res/icons/threeD.png"},
        {  ICON_SD , "/kval_res/icons/icon_sd.png"},
        {  ICO_ASPECT_1_78 , "/kval_res/icons/1_78.png"},
        {  ICO_CODEC_AAC , "/kval_res/icons/codec/aac.png"},
        {  ICO_CODEC_AC3, "/kval_res/icons/codec/ac3.png"},
        {  ICO_CODEC_DTS, "/kval_res/icons/codec/dts.png"},
        {  ICO_CODEC_DTSHDHRA, "/kval_res/icons/codec/dtshd_hra.png"},
        {  ICO_CODEC_DTSHDMA, "/kval_res/icons/codec/dtshd_ma.png"},
        {  ICO_CODEC_WMA, "/kval_res/icons/codec/wma.png"},
        {  ICO_CODEC_FLAC, "/kval_res/icons/codec/flac.png"},
        {  ICO_CODEC_MP2, "/kval_res/icons/codec/mp2.png"},
        {  ICO_CODEC_MP3, "/kval_res/icons/codec/mp3.png"},
        {  ICO_CODEC_LPCM, "/kval_res/icons/codec/pcm.png"},
        {  ICO_CODEC_OPUS, "/kval_res/icons/codec/ac3.png"},
        {  ICO_CODEC_VORBIS, "/kval_res/icons/codec/vorbis.png"},
        {  ICO_CODEC_H264 , "/kval_res/icons/codec/avc.png"},
        {  ICO_CODEC_H265 , "/kval_res/icons/codec/h265.png"},
        {  ICO_CODEC_MPEG2 , "/kval_res/icons/codec/mpeg2.png"},
        {  ICO_CODEC_VC1 , "/kval_res/icons/codec/vc1.png"},
        {  ICO_CODEC_VP9 , "/kval_res/icons/codec/vp9.png"},
        {  ICO_RES_480P , "/kval_res/icons/480.png"},
        {  ICO_RES_540P , "/kval_res/icons/540.png"},
        {  ICO_RES_576P , "/kval_res/icons/576.png"},
        {  ICO_RES_720P , "/kval_res/icons/720.png"},
        {  ICO_RES_1080P , "/kval_res/icons/1080.png"},
        {  ICO_RES_1440P , "/kval_res/icons/1440.png"},
        {  ICO_RES_2160P , "/kval_res/icons/2160.png"},
        {  ICO_HD_OFF , "/kval_res/icons/ico_hd_off.png"},
        {  ICO_SUBS_ON , "/kval_res/icons/subtitle_on.png"},
        {  ICO_SUBS_OFF , "/kval_res/icons/subtitle_off.png"},
        {  BACKGROUNG_ICON_VOD , "/kval_res/background/vod_background.jpg"},
        {  BACKGROUNG_ICON_VOD_ANIMATED , "/kval_res/background/vod"},
        {  VIDEO_ICON , "/kval_res/icons/video.png"},
        {  VIDEO_2_ICON , "/kval_res/icons/video_2.png"},
        {  MOVIE_FOLDER_ICON , "/kval_res/icons/movie_folder.png"},
        {  ICO_PREVIOUS, "/kval_res/icons/previous.png"},
        {  ICO_NEXT, "/kval_res/icons/next.png"},
        {  ICO_PREVIOUS_SMALL, "/kval_res/icons/previous_small.png"},
        {  ICO_NEXT_SMALL, "/kval_res/icons/next_small.png"},
        {  ICO_PREVIOUS_BLUE, "/kval_res/icons/previous_blue.png"},
        {  ICO_NEXT_BLUE, "/kval_res/icons/next_blue.png"},
        {  ICO_RATING_0 , "/kval_res/icons/rating0.png"},
        {  ICO_RATING_1 , "/kval_res/icons/rating1.png"},
        {  ICO_RATING_2 , "/kval_res/icons/rating2.png"},
        {  ICO_RATING_3 , "/kval_res/icons/rating3.png"},
        {  ICO_RATING_4 , "/kval_res/icons/rating4.png"},
        {  ICO_RATING_5 , "/kval_res/icons/rating5.png"},
        {  ICO_RATING_6 , "/kval_res/icons/rating6.png"},
        {  ICO_RATING_7 , "/kval_res/icons/rating7.png"},
        {  ICO_RATING_8 , "/kval_res/icons/rating8.png"},
        {  ICO_RATING_9 , "/kval_res/icons/rating9.png"},
        {  ICO_RATING_10 , "/kval_res/icons/rating10.png"},
        {  ICO_STAR_HALF , "/kval_res/icons/star_half.png"},
        {  ICO_STAR_EMPTY , "/kval_res/icons/star_empty.png"},
        {  ICO_START_VIDEO_V2 , "/kval_res/icons/start_play_v2.png"},
        {  ICO_START_VIDEO_V1 , "/kval_res/icons/start_video_v1.png"},
        {  ICO_LOGOUT , "/kval_res/icons/logout.png"},
        {  DEFAULT_COVER_IMAGE , "/kval_res/background/default_vod_cover.jpg"},
        {  ICO_PLAY , "/kval_res/icons/play.png"},
        {  ICO_PAUSE , "/kval_res/icons/pause.png"},
        {  ICO_NEXT_SKIP , "/kval_res/icons/next_skip.png"},
        {  ICO_PREVIOUS_SKIP , "/kval_res/icons/previous_skip.png"},
        {  OVERLAY_BACKGROUND , "/kval_res/background/darkBlue.png"},
        {  OVERLAY_BACKGROUND_HD , "/kval_res/overlay/background.png"},
        {  OVERLAY_BACKGROUND_2 , "/kval_res/overlay/background2.png"},
        {  OVERLAY_BACKGROUND_BLACK , "/kval_res/background/background_black.png"},
        {  OVERLAY_BACKGROUND_BLACK_2 , "/kval_res/background/background2_black.png"},
        {  OVERLAY_VIGNETTE_FULL , "/kval_res/overlay/vignette_full.png"},
        {  OVERLAY_VIGNETTE_BOTTOM , "/kval_res/overlay/vignette_bottom.png"},
        {  OVERLAY_VIGNETTE_FULL_ROUNDED , "/kval_res/overlay/vignette_full_rounded.png"},
        {  OVERLAY_BASE_COLOR , "/kval_res/overlay/base_color.png"},
        {  OVERLAY_BASE_COLOR_2 , "/kval_res/overlay/base_color.png"},
        {  OVERLAY_LIST_FOCUS , "/kval_res/overlay/list-focus.png"},
        {  OVERLAY_LIST_FOCUS_FLIPPED , "/kval_res/overlay/list-focus_flipped.png"},
        {  OVERLAY_SEPARATOR_FADED , "/kval_res/overlay/separatorFaded.png"},
        {  HD_ICON , "/kval_res/icons/HD.png"},
        {  SD_ICON , "/kval_res/icons/SD.png"},
        {  POSTER_FRAME , "/kval_res/frames/posterframe.png"},
        {  POSTER_FRAME_MASK , "/kval_res/frames/posterframemask.png"},
        {  POSTER_FRAME_GLOSS , "/kval_res/frames/postergloss.png"},
        {  INDICATOR_BACK , "/kval_res/icons/indicator.png"},
        {  FRAME_SQUARE_BIG , "/kval_res/frames/frame_Square.png"},
        {  FRAME_BANNER_VOD_CHOICE , "/kval_res/frames/bannerframevodChoice.png"},
        {  DEFAULT_BACKDORE_PNG , "/kval_res/background/moviesNoBackDoreImg.png"},
        {  SEPERATOR_MAIN_VIEW_SCREEN , "/kval_res/frames/separator.png"},
        {  HOME_RSS_INFO_BAR , "/kval_res/frames/homeInfoBar.png"},
        {  ALBUM_FRAME , "/kval_res/frames/albumframe.png"},
        {  ALBUM_FRAME_MASK , "/kval_res/frames/albumframemask.png"},
        {  INFO_OVERLAY_BLACK , "/kval_res/overlay/infoOverlayBlack.png"},
        {  INFO_OVERLAY_BLUE , "/kval_res/overlay/infoOverlayBlue.png"},
        {  GTIP_POINT , "/kval_res/icons/gripPoint.png"},
        {  GTIP_POINT_FIRST , "/kval_res/home/firstSelectedGrip.png"},
        {  GTIP_POINT_MIDDLE , "/kval_res/home/middleSelectedGrip.png"},
        {  GTIP_POINT_LAST , "/kval_res/home/lastSelectedGrip.png"},
        {  STAR_RATE , "/kval_res/icons/star.png"},
        {  HOME_VIDEO_ICON , "/kval_res/home/video.png"},
        {  HOME_TVSHOW_ICON , "/kval_res/home/tvshows.png"},
        {  HOME_VIDEO_CIRCLE_ICON , "/kval_res/home/videoaddons.png"},
        {  HOME_BACKGROUND_MORNING_1 , "/kval_res/background/Morning/Elan3_cropped.jpg"},
        {  BUSY_SPINNER , "/kval_res/icons/busy.png"},
        {  HOME_ICON , "/kval_res/home/home.png"},
        {  SEARCH_HOME_ICON , "/kval_res/home/search.png"},
        {  XML_MAIN_SCREEN_FILE , "/kval_cfg/main_screen_struct.xml"},
        {  LINE1_BACKGROUND , "/kval_res/home/lines_1.jpg"},
        {  LINE1_COMPLETE_BACKGROUND , "/kval_res/home/lines_1_complete.jpg"},
        {  LINE2_BACKGROUND , "/kval_res/home/lines_2.jpg"},
        {  LINE2_GREY_BACKGROUND , "/kval_res/home/lines_2_grey.jpg"},
        {  SPORT_WALLPAPER_BACKGROUND , "/kval_res/home/sport_wallpaper_foot.jpg"},
        {  LIVE_TV_BACK_2 , "/kval_res/home/tvBack2.jpg"},
        {  LIVE_TV_BACK_3 , "/kval_res/home/tvBack3.jpg"},
        {  LIVE_TV_BACK_1 , "/kval_res/home/logoScreen.png"},
        {  LIVE_SPORT_HORIZENTAL_SEPARATOR , "/kval_res/home/sliderBackground.png"},
        {  LIVE_SPORT_COMPET1_BACK , "/kval_res/home/liveSports/comp1Back.png"},
        {  LIVE_SPORT_COMPET2_BACK , "/kval_res/home/liveSports/comp2Back.png"},
        {  LIVE_SPORT_COMPET3_BACK , "/kval_res/home/liveSports/comp3Back.png"},
        {  LIVE_SPORT_LEAGUE_LOGOS_PATH , "/kval_res/home/liveSports/"},
        {  LIVE_SPORT_CLUBS_LOGOS_PATH , "/kval_res/home/liveSports/clubsLogos/"},
        {  LIVE_SPORT_BACK_1 , "/kval_res/home/liveSports/comp2Back.png"},
        {  LIVE_SPORT_BACK_2 , "/kval_res/home/liveSports/comp3Back.png"},
        {  LIVE_SPORT_VERTICAL_SEP , "/kval_res/home/vertical_sunken_sep.png"},
        {  LIVE_SPORT_FRAME_GALLERY , "/kval_res/home/frame_Gallery.png"},
        {  LIVE_SPORT_FOOT_LOGOS_BACK , "/kval_res/home/liveSports/footLogoBack.png"},
        {  LIVE_SPORT_FOOT_ALL_COMP , "/kval_res/home/liveSports/allCompetitions.png"},
        {  BOOT_BACKGROUNG_MORNING , "/kval_res/background/Morning/"},
        {  BOOT_BACKGROUNG_AFTERNOON , "/kval_res/background/afternoon/"},
        {  BOOT_BACKGROUNG_EVENING , "/kval_res/background/Evening/"},
        {  BOOT_KVAL_IP_ICONS , "/kval_res/background/kvalIcons.png"},
        {  KVAL_LOGO_LITTLE , "/kval_res/background/kvalLogoLittle.png"},
        {  STARTUP_AFTERNOON_WELCOME , "/kval_res/background/startupafternoon.png"},
        {  STARTUP_EVENING_WELCOME , "/kval_res/background/startupevening.png"},
        {  STARTUP_MORNING_WELCOME , "/kval_res/background/startupmorning.png"},
        {  KVAL_LOGO_BIG , "/kval_res/background/kvalLogoBig.png"},
        {  NOTIFICATION_MSG_BACK , "/kval_res/icons/notif_msg_back.png"},
        {  PLAYER_HINTS_BACK , "/kval_res/frames/playerHints.png"},
        {  LIVE_TV_BACK_IMG , "/kval_res/background/liveTvMain.jpg"},
        {  HOME_MESSAGE_ICON , "/kval_res/home/message.png"},
        {  USB_HOME_ICON , "/kval_res/home/usbStick.png"},
        {  HDD_HOME_ICON , "/kval_res/home/hdd.png"},
        {  HOME_LOCAL_MEDIA_PICS_BACK , "/kval_res/home/picturesBack.png"},
        {  HOME_LOCAL_MEDIA_PICS , "/kval_res/home/pictures.png"},
        {  HOME_LOCAL_MEDIA_MUSIC_BACK , "/kval_res/home/musicBack.png"},
        {  HOME_LOCAL_MEDIA_MUSIC , "/kval_res/home/music.png"},
        {  HOME_LOCAL_MEDIA_VIDEOS_BACK , "/kval_res/home/videosBack.png"},
        {  HOME_LOCAL_MEDIA_VIDEOS , "/kval_res/home/videoaddons.png"},
        {  HOME_MAILBOX_COMP1_BACK , "/kval_res/home/messageComp1Back.png"},
        {  HOME_MAILBOX_IMG , "/kval_res/home/mails.png"},
        {  HOME_MAILBOX_ONE_MAIL , "/kval_res/home/oneMailIcon.png"},
        {  HOME_MAILBOX_MSG_BUBBLE , "/kval_res/home/msgNumberBubble.png"},
        {  HOME_MAILBOX_TOTAL_MAILS , "/kval_res/home/mailList.png"},
        {  MAILBOX_BOX_ICON , "/kval_res/icons/mailBox.png"},
        {  MAILBOX_BOX_BACKGROUND , "/kval_res/background/mailBox2.jpg"},
        {  MAILBOX_BOX_SEEN_FLAG , "/kval_res/icons/seenFlag.png"},
        {  MAILBOX_BOX_SEEN_FLAG_SELECTED , "/kval_res/icons/seenFlagSelected.png"},
        {  MEDIA_BROWSER_ICON_HDD , "/kval_res/icons/mediaBrowser/DefaultHardDisk.png"},
        {  MEDIA_BROWSER_ICON_DIR , "/kval_res/icons/mediaBrowser/DefaultFolder.png"},
        {  MEDIA_BROWSER_ICON_AUDIO , "/kval_res/icons/mediaBrowser/DefaultMusic.png"},
        {  MEDIA_BROWSER_ICON_VIDEO , "/kval_res/icons/mediaBrowser/DefaultVideo.png"},
        {  MEDIA_BROWSER_ICON_IMAGE , "/kval_res/icons/mediaBrowser/DefaultPicture.png"},
        {  MEDIA_BROWSER_ICON_UNKNOWN , "/kval_res/icons/mediaBrowser/DefaultFile.png"},
        {  MEDIA_BROWSER_BACKGROUND , "/kval_res/background/local_media.jpg"},
        {  MEDIA_BROWSER_VIDEO_BACK , "/kval_res/background/moviesNoBackDoreImg.png"},
        {  MEDIA_BROWSER_MUSIC_BACK , "/kval_res/background/fallback_music.jpg"},
        {  SETTINGS_SYSTEM_ICON , "/kval_res/settings/system.png"},
        {  SETTINGS_NETWORK_ICON , "/kval_res/settings/network.png"},
        {  SETTINGS_PROFILE_ICON , "/kval_res/settings/profile.png"},
        {  SETTINGS_VOD_ICON , "/kval_res/settings/vod.png"},
        {  SETTINGS_LIVETV_ICON , "/kval_res/settings/live.png"},
        {  SETTINGS_INFO_ICON_SMALL, "/kval_res/settings/info_small.png"},
        {  SETTINGS_INFO_ICON_BIG , "/kval_res/settings/info_big.png"},
        {  SETTINGS_SELECT_ICON , "/kval_res/settings/select.png"},
        {  SETTINGS_EDIT_ICON , "/kval_res/settings/edit.png"},
        {  SETTINGS_ON_ICON , "/kval_res/settings/on.png"},
        {  SETTINGS_OFF_ICON , "/kval_res/settings/off.png"},
        {  SETTINGS_ACTION_ICON , "/kval_res/settings/action.png"},
        {  SETTINGS_SETTING_ICON, "/kval_res/settings/setting.png"},
        {  SETTINGS_BACKGROUND , "/kval_res/background/settings.jpg"},
        {  SETTINGS_ICON , "/kval_res/settings/settingsIcon.png"},
        {  SETTINGS_SEPARATOR_FADED, "/kval_res/settings/separatorFaded.png"},
        {  SETTINGS_WIFI_ICON_PREFIX, "/kval_res/settings/wifi"},
        {  VOLUME_ICON , "/kval_res/icons/volume.png"},
        {  MUTE_ICON , "/kval_res/icons/mute.png"},
        {  ICON_PAID , "/kval_res/icons/paid.png"},
        {  ICON_FREE , "/kval_res/icons/free.png"},
        {  DEFAULT_TEXT_FONT, "/kval_res/fonts/LightAlt.ttf"},
        {  DEFAULT_TEXT_FONT_LOW, "/kval_res/fonts/LightLow.ttf"},
        {  DEFAULT_TEXT_FONT_CAPS, "/kval_res/fonts/LightCaps.ttf"},
        {  DEFAULT_TEXT_BOLD_FONT, "/kval_res/fonts/Semilight.ttf"},
        {  ADVENT_TEXT_FONT, "/kval_res/fonts/advent-Re.otf"},
        {  MANGAS_TEXT_FONT, "/kval_res/fonts/manga.otf"},
        {  LIVE_TV_GALLERY_FONT, "/kval_res/fonts/bonohadavision.ttf"},
        {  XML_LIVE_SPORT_FILE, "/kval_cfg/live_sports.xml"},
        {  XML_CHANNEL_FILE , "/kval_cfg/livech.xml"},
        {  XML_FAV_CHANNEL_FILE , "/kval_cfg/favorite_channels.xml"},
        {  XML_VOD_FILE , "/kval_cfg/vod_tree.xml"},
        {  XML_VOD_QUICK_SETTING_FILE, "/kval_cfg/quick_settings.xml"},
        {  XML_SETTINGS_DISPLAY_FILE , "/kval_cfg/settingsDisplay.xml"},
        {  INFO_OVERLAY_RED, "/kval_res/overlay/infoOverlayRed.png"},
        {  WALL_FRAME_BASE, "/kval_res/frames/wall_overlay_base.png"},
        {  LIVE_SPORT_LOGO, "/kval_res/home/liveSportLogo.png"},
        {  MEDIA_BROWSER_ICON_USB, "/kval_res/icons/mediaBrowser/DefaultUsbDrive.png"},
        {  ADDON_ADD_ICON, "/kval_res/settings/addonAdd.png"},
        {  YT_LOGO_ICON, "/kval_res/settings/yt_logo.png"},
        {  YT_LOGO_APP, "/kval_res/icons/youtubeapplogo.png"},
        {  YT_APP_BACK, "/kval_res/background/yt_app_back.jpg"},
        {  MAIN_APPFRAME, "/kval_res/frames/mainAppFrame.png"},
        {  MAIN_APPFRAME_MASK, "/kval_res/frames/mainAppFrameMask.png"},
        {  MAIN_APPFRAME_SHADOW, "/kval_res/frames/mainAppFrameShadow.png"},
        {  APP_FRAME, "/kval_res/frames/albumframe.png"},
        {  APP_FRAME_MASK, "/kval_res/frames/albumframemask.png"},
        {  APP_PLUS_BACKGROUND, "/kval_res/home/appPlusBack.jpg"},
        {  SCREEN_APP_FOREGROUND_1, "/kval_res/home/screenAppVersion1.png"},
        {  SCREEN_APP_FOREGROUND_1_REF, "/kval_res/home/screenAppVersion1Ref.png"},
        {  SCREEN_APP_SHININGCORNER_1, "/kval_res/home/screenAppVersion1Shadow.png"},
        {  SCREEN_APP_FOREGROUND_2, "/kval_res/home/screenAppVersion2.png"},
        {  SCREEN_APP_SHININGCORNER_2, "/kval_res/home/screenAppVersion2Shadow.png"},
        {  SCREEN_APP_FOREGROUND_3, "/kval_res/home/screenAppVersion3.png"},
        {  SCREEN_APP_SHININGCORNER_3, "/kval_res/home/screenAppVersion3Shadow.png"},
        {  WEATHER_APP_BACK, "/kval_res/home/weatherBack.png"},
        {  WEATHER_APP_ICON, "/kval_res/home/weatherIcon.png"},
        {  APPS_BACKGROUND, "/kval_res/background/apps.jpg"},
        {  APPS_BLOCK_BACK, "/kval_res/icons/myapps/appBlock.png"},
        {  APPS_BLOCK_SEP, "/kval_res/icons/myapps/appBlockSeparator.png"},
        {  APPS_ICONS, "/kval_res/icons/myapps/appIcon.png"},
        {  APPS_SELECTOR, "/kval_res/icons/myapps/selector.png"},
        {  APPS_SELECTOR2, "/kval_res/icons/myapps/selector2.png"},
        {  APPS_FADED, "/kval_res/icons/myapps/summaryFade.png"},
        {  APPS_UPGRADE_ICON, "/kval_res/icons/myapps/upgradeIcon.png"},
        {  APPS_VIEW_BACK, "/kval_res/icons/myapps/appViewBack.png"},
        {  APPS_VIEW_ALL_ICO, "/kval_res/icons/myapps/all.png"},
        {  APPS_VIEW_FAV_ICO, "/kval_res/icons/myapps/favorite.png"},
        {  APPS_VIEW_GAMES_ICO, "/kval_res/icons/myapps/games.png"},
        {  APPS_VIEW_INSTALLED_ICO, "/kval_res/icons/myapps/installed.png"},
        {  APPS_VIEW_MISC_ICO, "/kval_res/icons/myapps/misc.png"},
        {  APPS_VIEW_STORE_ICO, "/kval_res/icons/myapps/store.png"},
        {  APPS_VIEW_VID_ICO, "/kval_res/icons/myapps/video.png"},
        {  APPS_VIEW_SEARCH_ICO, "/kval_res/icons/myapps/search.png"},
        {  APPS_VIEW_SELCTOR_CAT, "/kval_res/icons/myapps/selectorCategory2.png"},
        {  APPS_VIEW_MASKGRID, "/kval_res/icons/myapps/girdMask.png"},
        {  APPS_VIEW_BACKMASKGRID, "/kval_res/icons/myapps/backGirdMask.png"},
        {  APPS_VIEW_MASKGRIDDIAG, "/kval_res/icons/myapps/girdMaskDiag.png"},
        {  APPS_VIEW_SPINNER_BACK, "/kval_res/icons/myapps/spinnerBack.png"},
        {  APPS_VIEW_SPINNER, "/kval_res/icons/myapps/spinner.png"},
        {  APPS_CAT_SELECTOR, "/kval_res/icons/myapps/categorySelector.png"},
        {  APPS_RECTWARE_SELECTOR, "/kval_res/icons/myapps/rectangleWareSelector.png"},
        {  APPS_COVERWARE_SELECTOR, "/kval_res/icons/myapps/coverWareSelector.png"},
        {  APPS_DIAG_WINDOW, "/kval_res/icons/myapps/diagPrompt.png"},
        {  APPS_DIAG_BUTTON, "/kval_res/icons/myapps/diagButton.png"},
        {  APPS_DIAG_SELECTOR, "/kval_res/icons/myapps/diagButSelector.png"},
        {  APPS_PROGRESS_BAR_BACK, "/kval_res/icons/myapps/progressBarBack.png"},
        {  APPS_PROGRESS_BAR_HELPER, "/kval_res/icons/myapps/progressBarHelper.png"},
        {  APPS_MENU_ICON, "/kval_res/icons/myapps/menuIcon.png"},
        {  APPS_RECTANGLEWARE_REF, "/kval_res/icons/myapps/rectangleWareBlock.png"},
        {  APPS_LISTRECTANGLEWARE_REF, "/kval_res/icons/myapps/listRectangleWareBlock.png"},
        {  APPS_LISTCOVERWARE_REF, "/kval_res/icons/myapps/listCoverWareBlock.png"},
        {  APPS_BOXWARE_REF, "/kval_res/icons/myapps/boxWareBlock.png"},
        {  APPS_COVERWARE_REF, "/kval_res/icons/myapps/coverWareBlock.png"},
        {  APPS_LISTBOXWARE_REF, "/kval_res/icons/myapps/listBoxWareBlock.png"},
        {  APPS_LISTRECT_SELECTOR, "/kval_res/icons/myapps/listViewRectSelector.png"},
        {  APPS_RECTANGLEWARE_MASK, "/kval_res/icons/myapps/rectangleWareMask.png"},
        {  APPS_COVERWARE_MASK, "/kval_res/icons/myapps/coverWareMask.png"},
        {  APPS_CTX_SHADOW, "/kval_res/icons/myapps/ctxShadow.png"},
        {  APPS_CTX_HEADER, "/kval_res/icons/myapps/ctxHeader.png"},
        {  APPS_CTX_BORDER, "/kval_res/icons/myapps/ctxBorder.png"},
        {  APPS_CTX_BODY, "/kval_res/icons/myapps/ctxBody.png"},
        {  APPS_CTX_MENU_SELECTOR, "/kval_res/icons/myapps/ctxMenuSelector.png"},
        {  APPS_CTX_MASK, "/kval_res/icons/myapps/girdMaskCtx.png"},
        {  APPS_LIST_MENU_HEADER, "/kval_res/icons/myapps/listMenuHeader.png"},
        {  APPS_LIST_MENU_BODY, "/kval_res/icons/myapps/listMenuBody.png"},
        {  APPS_LIST_MENU_BORDER, "/kval_res/icons/myapps/listMenuBorder.png"},
        {  APPS_LIST_MENU_SHADOW, "/kval_res/icons/myapps/listMenuShadow.png"},
        {  APPS_LIST_MENU_SELECTOR, "/kval_res/icons/myapps/listMenuSelector.png"},
        {  APPS_APP_INFOS_BACK, "/kval_res/icons/myapps/appInfoWindow.png"},
        {  APPS_APP_INFOS_MASK, "/kval_res/icons/myapps/appInfoMask.png"},
        {  APPS_MOTION_GRAPHICS, "/kval_res/motion_graphics/app_motion_graphics.mp4"},
        {  KVAL_LOCAL_HOST_LINK, ""},
        {  KVAL_WIZI_LINK, ""},
        {  BLUE_BUTTON_ICO, "/kval_res/icons/myapps/blueButton.png"},
        {  BLUE_PANEL_BACK, "/kval_res/background/backBluePanel.png"},
        {  BLUE_PANEL_SELECTOR, "/kval_res/background/bluePanelSelector.png"},
        {  BLUE_PANEL_SEPARATOR, "/kval_res/background/bluePanelSeparator.png"},
        {  VOD_POINT_SEP, "/kval_res/icons/vodpoint.png"},
        {  VO_LANG_ICON, "/kval_res/icons/vo.png"},
        {  VOST_LANG_ICON, "/kval_res/icons/vostfr.png"},
        {  VF_LANG_ICON, "/kval_res/icons/vf.png"},
        {  MULTI_LANG_ICON, "/kval_res/icons/multi.png"},
        {  BLURAY_QUAL_ICON, "/kval_res/icons/bluray.png"},
        {  LIGHT_QUAL_ICON, "/kval_res/icons/lightbr.png"},
        {  DVD_QUAL_ICON, "/kval_res/icons/dvd.png"},
        {  MAIN_REBOOT_ICON, "/kval_res/icons/reboot.png"},
    };

    int getEnumFromStr(QString id);
    virtual ~KvalConfigManagerResources() {}
};

/**
 * @brief The CM_ConfigManager class
 */
class KvalConfigManager: public KvalConfigManagerResources
{
    Q_OBJECT
    Q_DISABLE_COPY(KvalConfigManager)

public:
    static KvalConfigManager *Instance(){
        static KvalConfigManager instance;
        return &instance;
    }

    QString qmlGetStr(str_ids id);
    QString qmlGetPath(path_ids id);
    QString xmlGetStr(QString &id);
    QString xmlGetStr(QString &&id) { return xmlGetStr(id); }
    QString get_base_res_path();
    QString translate_path(const QString &path);
    QString get_path(path_ids id);
    QString get_exec_path(path_ids id);
    QString getHomePath() { return m_home_path; }

private:
    KvalConfigManager();
    virtual ~KvalConfigManager() = default;

private:
    QString m_home_path;
    QString m_script_home_path;
    QMutex m_path_mtx;
};

/**
 * @brief cfgManager
 * @return
 */
#define CfgObj KvalConfigManager::Instance()

/**
 * @brief The CM_CM_ConfigManagerElement class
 */
class KvalConfigManagerElement: public KvalConfigManagerResources
{
    Q_OBJECT
    Q_PROPERTY(QString retranslate READ getRetranslate NOTIFY languageChanged)

public:
    KvalConfigManagerElement() {}
    virtual ~KvalConfigManagerElement() {}

    Q_INVOKABLE QString qmlStr(str_ids id);
    Q_INVOKABLE QString qmlHomePath() { return CfgObj->getHomePath(); }
    Q_INVOKABLE QString qmlResPath() {  return CfgObj->get_base_res_path(); }
    Q_INVOKABLE QString translate_path(const QString &path){
        return CfgObj->translate_path(path);
    }
    Q_INVOKABLE QString qmlGetPath(path_ids id);
    Q_INVOKABLE QString xmlGetStr(QString id);
    Q_INVOKABLE QString qmlGetSrvPiconPath(QString channelName);
    Q_INVOKABLE void langChanged();
    Q_INVOKABLE void updateLiveTvSrvAddress();
    QString getRetranslate();

Q_SIGNALS:
    void languageChanged();

private:
    QString m_livetv_srv_address;

};

#endif // KVAL_CONFIGMANAGER_H
